name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
  workflow_dispatch:
    inputs:
      dbgsdk:
        type: boolean
        description: compile with debug PS2SDK
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git bash p7zip

    - name: Workaround permission issue
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - uses: actions/checkout@v4
    - run: |
        git fetch --prune --unshallow

    - name: Compile debug SDK
      if: github.event.inputs.dbgsdk == 'true'
      run: |
        git clone https://github.com/ps2dev/ps2sdk/
        cd ps2sdk
        make clean debug install

    - name: Compile project
      run: |
        make clean all pack MECHAEMU=1

    - name: Get version
      run: |
        echo "PROGVER=$(make progver)" >> $GITHUB_ENV

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: SC2Maker
        path: SC2Maker_*.7z

    - name: Create pre-release
      if: github.ref == 'refs/heads/main'
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development build"
        files: |
               SC2Maker_*.7z

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ env.PROGVER }}"
        title: "v${{ env.PROGVER }} Release"
        files: |
               SC2Maker_*.7z
